export default [
    {
        name:'Home',
        screenName:'Home',
        iconType:'MaterialIcons',
        iconName:'home'
    },
    {
        name:'Profile',
        screenName:'Profile',
        iconType:'Feather',
        iconName:'user'
    },
    {
        name:'Post a Job',
        screenName:'JobPost',
        iconType:'MaterialIcons',
        iconName:'post-add'
    },
    {
        name:'Settings',
        screenName:'Settings',
        iconType:'MaterialIcons',
        iconName:'settings'
    },
    {
        name:'About',
        screenName:'About',
        iconType:'Feather',
        iconName:'info'
    },
    {
        name:'Logout',
        screenName:'Logout',
        iconType:'Feather',
        iconName:'log-out'
    },
 ]